#######FUNCION QUE SE HAGA DESDE AHORA DEBE DECIR QUE HACE Y QUE RETORNA##########

#DESARROLLE UNA FUNCION QUE RECIBA UNA LISTA Y ELIMINE TODOS LOS ELEMENTOS NEGATIVOS DE LA LISTA Y RETORNE LA LISTA ACTUALIZADA